# Generated by Django 3.2.16 on 2022-12-11 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre Localidad')),
                ('cp', models.CharField(max_length=10, verbose_name='Codigo Postal')),
                ('provincia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre/s')),
                ('apellido', models.CharField(max_length=150)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_nac', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('tipo_iva', models.CharField(choices=[('CF', 'Consumidor Final'), ('RI', 'Responsable Inscripto'), ('MT', 'Monotributo')], default='CF', max_length=2, verbose_name='Tipo de IVA')),
                ('localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='libros.localidad')),
            ],
        ),
    ]
